import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Database } from '../src/database.js';
import { startHttp } from '../src/http.js';

test('API local expõe saúde, dados e interface web', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'codex-telegram-http-'));
  const db = new Database(join(dir, 'bridge.sqlite'));
  const server = startHttp({ telegramToken: 'test', allowedUserId: 1, projects: [{ id: 'demo', name: 'Demo', cwd: '/tmp/demo' }], codexCommand: 'codex', codexModels: [], codexReasoningEfforts: ['low', 'medium', 'high'], skillsDir: join(dir, 'skills'), dbPath: join(dir, 'bridge.sqlite'), httpHost: '127.0.0.1', httpPort: 0 }, db, async (text) => { const id = db.createTask('demo', 'thread-test', text); return { taskId: id }; });
  await new Promise<void>((resolve) => server.once('listening', resolve));
  const port = (server.address() as { port: number }).port;
  assert.equal((await (await fetch(`http://127.0.0.1:${port}/health`)).json() as any).status, 'ok');
  const docs = await fetch(`http://127.0.0.1:${port}/docs`);
  assert.equal(docs.status, 200); assert.match(await docs.text(), /SwaggerUIBundle/);
  const swaggerBundle = await fetch(`http://127.0.0.1:${port}/docs/swagger-ui-bundle.js`);
  assert.equal(swaggerBundle.status, 200); assert.match(swaggerBundle.headers.get('content-type') || '', /javascript/);
  const openapi = await fetch(`http://127.0.0.1:${port}/openapi.json`);
  assert.equal(openapi.status, 200); assert.equal((await openapi.json() as any).openapi, '3.0.3');
  assert.match(await (await fetch(`http://127.0.0.1:${port}/`)).text(), /Codex Telegram Bridge/);
  const settingsPage = await fetch(`http://127.0.0.1:${port}/configuracoes`);
  assert.equal(settingsPage.status, 200);
  assert.match(await settingsPage.text(), /settings-root/);
  const settings = await (await fetch(`http://127.0.0.1:${port}/api/settings`)).json() as any;
  assert.equal(settings.readOnly, true);
  assert.equal(settings.settings.length, 18);
  assert.deepEqual(settings.settings.find((item: any) => item.key === 'TELEGRAM_BOT_TOKEN').value, { configured: true });
  const validDraft = await fetch(`http://127.0.0.1:${port}/api/settings/validate`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ PROJECTS_JSON: '[{"id":"demo","name":"Demo","cwd":"/tmp/demo"}]', HTTP_PORT: '8787', CODEX_MODELS_JSON: '[]', CODEX_REASONING_EFFORTS_JSON: '["low"]' }) });
  assert.equal(validDraft.status, 200); assert.equal((await validDraft.json() as any).valid, true);
  const invalidDraft = await fetch(`http://127.0.0.1:${port}/api/settings/validate`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ HTTP_PORT: '70000', CODEX_REASONING_EFFORTS_JSON: '["invalid"]' }) });
  assert.equal(invalidDraft.status, 422); assert.equal((await invalidDraft.json() as any).valid, false);
  assert.equal((await (await fetch(`http://127.0.0.1:${port}/projects`)).json() as any).projects.length, 1);
  const helloWorld = await fetch(`http://127.0.0.1:${port}/hello-world`);
  assert.equal(helloWorld.status, 200);
  assert.match(await helloWorld.text(), /Hello World!/);
  const command = await fetch(`http://127.0.0.1:${port}/commands`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text: 'teste pelo navegador', projectId: 'demo' }) });
  assert.equal(command.status, 202); assert.equal((await command.json() as any).accepted, true);
  await new Promise<void>((resolve) => server.close(() => resolve())); db.close(); rmSync(dir, { recursive: true, force: true });
});
