const $ = (id) => document.getElementById(id);
const labels = { queued: 'na fila', running: 'executando', waiting_user: 'aguardando', completed: 'concluída', failed: 'falhou', interrupted: 'interrompida', unknown: 'indeterminada' };
let currentTaskId;
const savedTheme = localStorage.getItem('bridge-theme'); if (savedTheme === 'light') { document.documentElement.dataset.theme = 'light'; $('theme-toggle').innerHTML = '☾ <span>Modo escuro</span>'; }
const date = (value) => value ? new Date(value.replace(' ', 'T') + (value.endsWith('Z') ? '' : 'Z')).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }) : '—';
async function get(path) { const response = await fetch(path); if (!response.ok) throw new Error(`${response.status}`); return response.json(); }
function renderTasks(tasks) { $('task-count').textContent = tasks.length; $('running-count').textContent = tasks.filter((t) => t.status === 'running').length; $('tasks').innerHTML = tasks.length ? tasks.map((task) => `<article class="task"><div><div class="task-text">${escapeHtml(task.text)}</div><div class="task-meta">#${task.id} · ${escapeHtml(task.projectId)} · ${date(task.createdAt)}</div></div><span class="badge badge-${task.status}">${labels[task.status] || task.status}</span></article>`).join('') : '<div class="empty">Nenhuma tarefa registrada.</div>'; }
function renderProjects(projects) { $('project-count').textContent = projects.length; $('projects').innerHTML = projects.length ? projects.map((p) => `<article class="project"><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.cwd)}</small></article>`).join('') : '<div class="empty">Nenhum projeto cadastrado.</div>'; $('project-select').innerHTML = projects.map((p) => `<option value="${escapeHtml(p.id)}">${escapeHtml(p.name)}</option>`).join(''); }
function renderEvents(events) { const grouped = []; for (const event of events) { const previous = grouped[grouped.length - 1]; if (previous && event.kind === 'text' && previous.kind === 'text' && previous.taskId === event.taskId) previous.text = event.text + previous.text; else grouped.push({ ...event }); } $('event-count').textContent = grouped.length; $('events').innerHTML = grouped.length ? grouped.slice(0, 12).map((event) => `<article class="event"><span class="event-kind">${escapeHtml(event.kind)}</span><div><div class="event-text">${renderMarkdown(event.text)}</div><div class="event-meta">tarefa #${event.taskId || '—'} · ${date(event.createdAt)}</div></div></article>`).join('') : '<div class="empty">Nenhum evento registrado para esta tarefa.</div>'; }
async function refresh() { try { const [health, status, projects] = await Promise.all([get('/health'), get('/status'), get('/projects')]); if (currentTaskId === undefined) currentTaskId = status.tasks?.[0]?.id; const events = await get(currentTaskId ? `/events?taskId=${currentTaskId}` : '/events?taskId=0'); $('health-dot').className = 'dot ok'; $('health-label').textContent = health.status === 'ok' ? 'Bridge conectado' : 'Bridge em atenção'; renderTasks(status.tasks || []); renderProjects(projects.projects || []); renderEvents(events.events || []); $('last-update').textContent = `Atualizado às ${new Date().toLocaleTimeString('pt-BR')}`; } catch { $('health-dot').className = 'dot error'; $('health-label').textContent = 'Bridge indisponível'; } }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character])); }
function renderMarkdown(value) { let text = escapeHtml(value); const blocks = []; text = text.replace(/```(?:[\w-]+)?\n?([\s\S]*?)```/g, (_, code) => { const token = `@@CODE${blocks.length}@@`; blocks.push(`<pre><code>${code.trim()}</code></pre>`); return token; }); text = text.replace(/^### (.+)$/gm, '<h4>$1</h4>').replace(/^## (.+)$/gm, '<h3>$1</h3>').replace(/^# (.+)$/gm, '<h3>$1</h3>').replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/`([^`]+)`/g, '<code>$1</code>').replace(/^[*-] (.+)$/gm, '• $1').replace(/\n/g, '<br>'); return text.replace(/@@CODE(\d+)@@/g, (_, index) => blocks[Number(index)]); }
$('refresh').addEventListener('click', refresh); refresh(); setInterval(refresh, 3000);
$('command-form').addEventListener('submit', async (event) => { event.preventDefault(); const text = $('command-text').value.trim(); if (!text) return; const feedback = $('command-feedback'); currentTaskId = null; renderEvents([]); feedback.textContent = 'Enviando para o Codex...'; try { const response = await fetch('/commands', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text, projectId: $('project-select').value }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Não foi possível enviar'); currentTaskId = result.taskId; feedback.textContent = `Tarefa #${result.taskId} aceita. Acompanhando somente esta execução.`; $('command-text').value = ''; await refresh(); } catch (error) { feedback.textContent = `Erro: ${error.message}`; } });
$('theme-toggle').addEventListener('click', () => { const light = document.documentElement.dataset.theme !== 'light'; document.documentElement.dataset.theme = light ? 'light' : 'dark'; localStorage.setItem('bridge-theme', light ? 'light' : 'dark'); $('theme-toggle').innerHTML = light ? '☾ <span>Modo escuro</span>' : '☼ <span>Modo claro</span>'; });
